## \u5E94\u7528\u540D\u79F0
#spring.application.name=gulimall-coupon
## \u5E94\u7528\u670D\u52A1 WEB \u8BBF\u95EE\u7AEF\u53E3
#server.port=8080

#\u6D4B\u8BD5\u6CE8\u518C\u4E2D\u5FC3\uFF0C\u83B7\u53D6\u4FE1\u606F @Value("${user.name}") "X10ti-S",   @Value("${user.age}") 23
#user.name=\u674E\u65FA
#
#user.age=24


